#!/usr/bin/env bash
#
# Run tests
#
set -e

echo '[script/test] Running tests'
PACKAGES=$(go list ./... | grep -v '/vendor/')
if [ "${CI}" ]; then
  goveralls -service=travis-ci
else
  go test -cover $PACKAGES
fi

# vim: ft=sh:
